default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mybudgetapp_development
  username: postgres
  password: <%= ENV['password']%>

test:
  <<: *default
  database: mybudgetapp_test
  username: postgres
  password: <%= ENV['password']%>

production:
  <<: *default
  database: mybudgetapp_production
  username: mybudgetapp
  password: <%= ENV["MYBUDGETAPP_DATABASE_PASSWORD"] %>
